### ISSUE TITLE
make graphs more compact

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#14]
Currently the graphs are very far-spaced, it would be great, if they could be made more compact (i.e. shorter links). I suspect that there is a parameter that controls this, it would be good, if there were a slider for that parameter, so that that the user can control this until he/she is satisfied with the result.

**Comment by Shadow992** [comment]
A great idea but very tough to implement. The overall graph size (when "layouted") is estimated by a heuristic. This heuristic determines the spacing between single graphs. Therefore it is really difficult to find something every graph (small and big, widespread and clumbed ,...) look beatiful with. The current parameter set seems to work in most cases reasonably well.

However a slider is kind of possible but I would prefer a " Menu" or "Button" because the layout has to be recalculated for every changed value. However I will have an eye on it, maybe offer three different menu options "Wide", " Normal" and "small" Spacing.

**Comment by kohlhase** [comment]
thanks for the clarification. I do not insist on a slider; a menu would also work, but three values may be a bit coarse. 
Maybe we can also have keyboard shortcuts like C-+ and C-- that increase and decresase density by one increment?

**Comment by Shadow992** [comment]
This will end in like the same problem. Whenever decreasing value by one, the user have to wait a few seconds until he is able to see the "new layout". So if someone wants to go 10x times lower he has to wait about 10*2s = 20s until he reached his goal. I would suggest to just add more values to the Menu/Selectbox or add another button which says "Relayout" and calculates the layout only when clicked on this button. On this way we also could use a slider.

**Comment by kohlhase** [comment]
I think you will just need to experiment what works best (for you), and then show it to me so that I can complain (and you have founded arguments against my ideas).

**Comment by Shadow992** [comment]
Also implemented now.
I guess the Menu-Select is the best solution we can come up with.
The slider looked really ugly and needed much text to explain exactly what he was for. A Inputbox where you are able to enter values was kind of "confusing" because between two values (e.g. "1" and "2") you did nearly see no difference in layout.

So the Comobox/Selectbox seems to be the best solution, see e.g:
http://neuralocean.de/graph/theorygraph.php?uri=http://neuralocean.de/graph/test/pvs.json

We could also add a few more Spacing-Levels if needed ("Minimum Spacing", "Maximum Spacing", ...)

**Comment by kohlhase** [comment]
I like the menu, only that it does not change anything, do I have to do somthing else than select?

**Comment by Shadow992** [comment]
Ahh yeah you have to click on the "Layout-Button" again. But I think I should really change this.

**Comment by kohlhase** [comment]
indeed, the re-layout should be triggered by selecting a new value.

**Comment by kohlhase** [comment]
but when that is changed, I really like the enhancement.
