### ISSUE TITLE
some kind of progress indicator (JSON received) 

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#7]
I have looked at the NASA library, and I am getting the spinner for minutes (that is probably OI, since this is a large graph). But it would be very good to have some kind of progress indicator. 
As there is probably none for pure graph layout, It would be good, if we could give some kind of feedback, e.g. something like
`Graph data received`
and then 
```formatting ??? nodes and ??? edges```
and then if ??? > 1000 something like 
`this may take a while`

This would give the user some sense of what is happening

In particular, If there is no graph data from MMT (e.g. if MMT is dead and needs to be restarted), this would give useful hints.

**Comment by kohlhase** [comment]
Alternatively for big ??? one could ask something like `really format a graph of size ???, you could try a subgraph`

**Comment by Shadow992** [comment]
Added statusbar and surpisingly the bottleneck is not they layouting but the downloading (at least for me). Downloading takes about 3-5secs and layouting less than 1s. I close this issue as StatusBar is added and Layouting seems to be no problem at all.

**Comment by kohlhase** [comment]
can I see this anywhere?

**Comment by Shadow992** [comment]
You can see this there:
http://neuralocean.de/graph/theorygraph.php?uri=http://neuralocean.de/graph/test/nasa.json

But I just went more in depth in this problem and the big problem is, that a statusbar while javascript is processing something is nor possible (at least it depends hard on the browser used). Because Javascript and the HTML-Render-Engine shares one thread. This means while doing heavy javascript processing, HTML will not be updated and vice versa.

Therefore it only looks like downloading graph takes that long. In reality downloading graph was the last time the HTML-Render-Engine was updated. Unfortunately it is very tough to circumvent this problem... :/

**Comment by kohlhase** [comment]
Oh, this is impressively better. I think we can close this issue. Just the "downloading graph" is good, can you add "received ??? nodes" after downloading is finished? Then I would consider this fixed.

**Comment by Shadow992** [comment]
Yep I will add this

**Comment by kohlhase** [comment]
I really like the fact that we have an indication of how many nodes there are in the graph left over.
